### ISSUE TITLE
DefaultHeader 偏位了

### ISSUE THREAD

**Issue by banli17** [react-native-studio/react-native-SmartRefreshLayout#10]
箭头 和 指示器位置 不在一条线上。

![1](https://user-images.githubusercontent.com/12556069/42562709-05d49a56-852f-11e8-94ae-ae675af88f63.png)
![2](https://user-images.githubusercontent.com/12556069/42562714-07869354-852f-11e8-89d9-e86e4606889b.png)

**Comment by 2534290808** [comment]
已经修复了，0.5.6版本即可
