### ISSUE TITLE
滚动惯性，header 会在惯性时显示。怎么去掉呢

### ISSUE THREAD

**Issue by banli17** [react-native-studio/react-native-SmartRefreshLayout#11]
就是先让列表滚动一些，快速往下一拉，放手，列表的惯性还会弹些距离。这时会显示出刷新组件。这个应该是不需要的。应该是只手指按住下滑，才触发，而不是惯性也可以触发

**Comment by 2534290808** [comment]
已经修复0.5.5版本，设置SmartRefreshControl的overScrollBounce属性为false即可
