### ISSUE TITLE
下拉刷新时触发ListView列表中的onPress方法

### ISSUE THREAD

**Issue by yhyfms** [react-native-studio/react-native-SmartRefreshLayout#14]
下拉刷新时触发ListView列表中的onPress方法，如何避免触发点击事件？

**Comment by 2534290808** [comment]
请问能再具体点吗？

**Comment by yhyfms** [comment]
哦哦，刚刚我又仔细看了下ListView的例子，使用插件时必须放在ScrollView内，如果想使用ListView就必须借助renderScrollComponent，是吗？

**Comment by 2534290808** [comment]
那你是使用什么方式？

**Comment by yhyfms** [comment]
我是直接用在了ListView上了

**Comment by 2534290808** [comment]
也可直接使用ListView的refreshControl属性，具体请看ListViewExample1，谢谢

**Comment by 2534290808** [comment]
你说的这种情况我使用以上两种方式都没有出现

**Comment by yhyfms** [comment]
![test](https://user-images.githubusercontent.com/26535896/43375474-dfa35968-93e7-11e8-8b0b-972261dfc23b.png)
在下拉刷新在一个item上时，就会弹出alert

**Comment by 2534290808** [comment]
v0.5.8已经修复该问题，谢谢你的issue！
