### ISSUE TITLE
安卓运行的时候报错了

### ISSUE THREAD

**Issue by iwangx** [react-native-studio/react-native-SmartRefreshLayout#16]
Error:(42, 65) 错误: 类型参数ReactSmartRefreshLayout不在类型变量T的范围内
其中, T是类型变量:
T扩展已在类 ViewGroupManager中声明的ViewGroup
```
public class ReactSmartRefreshLayout extends SmartRefreshLayout {
       ^
  找不到android.support.v4.view.NestedScrollingParent的类文件
警告: 未知的枚举常量 Scope.LIBRARY
原因: 找不到android.support.annotation.RestrictTo$Scope的类文件


public class SmartRefreshLayoutManager extends ViewGroupManager<ReactSmartRefreshLayout>{
                                                                ^
  其中, T是类型变量:
    T扩展已在类 ViewGroupManager中声明的ViewGroup

        smartRefreshLayout.setEnableLoadMore(false);//暂时禁止上拉加载
                          ^
  符号:   方法 setEnableLoadMore(boolean)
  位置: 类型为ReactSmartRefreshLayout的变量 smartRefreshLayout
```

**Comment by iwangx** [comment]
public class ReactSmartRefreshLayout extends SmartRefreshLayout {
       ^
  找不到android.support.v4.view.NestedScrollingParent的类文件
警告: 未知的枚举常量 Scope.LIBRARY
  原因: 找不到android.support.annotation.RestrictTo$Scope的类文件

**Comment by 2534290808** [comment]
请提供Android版本，谢谢

**Comment by iwangx** [comment]
@2534290808 怎么看安卓版本，纯前端开发。。。。不知道哪里看，我是点击Run "app" 出错的

**Comment by iwangx** [comment]
@2534290808 大哥。快怎么办啊？我的react-native版本是0.55.4 ，`react-native-smartrefreshlayout`是最新的`0.5.8`的

**Comment by iwangx** [comment]
![image](https://user-images.githubusercontent.com/11516318/43562095-11a6ddc4-964d-11e8-812b-8f6a35530ada.png)

**Comment by iwangx** [comment]
![image](https://user-images.githubusercontent.com/11516318/43562156-6eeb0618-964d-11e8-8f93-d59018901f6e.png)

**Comment by 2534290808** [comment]
请看示例，我的示例也是0.55.4的

**Comment by 2534290808** [comment]
请使用react-native run-android运行
