### ISSUE TITLE
cannot red property "props" of undefined

### ISSUE THREAD

**Issue by allenxieyusheng** [react-native-studio/react-native-SmartRefreshLayout#19]

**Comment by 2534290808** [comment]
Can you give me some specific error information?

**Comment by 2534290808** [comment]
能给我一些具体的错误❎信息吗？

**Comment by NikiLee2016** [comment]
I think you din't write the constructor like this:
constructor(props) {
        super(props);
}
Maybe you didn't give 'props' to the super function, I met the same exception before and this is my solution.

**Comment by 2534290808** [comment]
我这边没有出现过这种情况，你能定位到是哪个文件吗？谢谢

**Comment by NikiLee2016** [comment]
不是, 是我之前在项目中遇见过这个错误. 在smartRefreshLayout组件中, 我也没遇见过这个错误. 表达不准确, 抱歉了

**Comment by 2534290808** [comment]
哦，那会不会不是这个组件引起的错误❎？

**Comment by NikiLee2016** [comment]
那要看楼主能不能提供报错信息截图了. 很可能不是

**Comment by NikiLee2016** [comment]
建议先别close, 我不是楼主😂

**Comment by allenxieyusheng** [comment]
找到问题就close吧。我也只是试了集成了一下子～然后就没试了～～

**Comment by 2534290808** [comment]
好的👌:smile:
