### ISSUE TITLE
在RN0.57.6中的打包会出错

### ISSUE THREAD

**Issue by liguanhan** [react-native-studio/react-native-SmartRefreshLayout#26]
RN版本:0.57.6;
库版本:0.6.3;
安卓版本:8.1.0;
android/build.gradle下的配置信息:
![_20181206150307](https://user-images.githubusercontent.com/24800090/49567254-1fc94800-f968-11e8-8b49-64395c319fda.png)
![image](https://user-images.githubusercontent.com/24800090/49567274-31aaeb00-f968-11e8-9f27-acad7e628aad.png)
app/build.gradle下的配置信息:
![image](https://user-images.githubusercontent.com/24800090/49567298-412a3400-f968-11e8-8a9a-68d8f1c36973.png)
报错信息:
![image](https://user-images.githubusercontent.com/24800090/49567379-7898e080-f968-11e8-855e-423fbb8aa4da.png)

**Comment by liguanhan** [comment]
请问作者如何解决呢?还是我这里的配置有问题啊,不是很想退回低版本.

**Comment by 2534290808** [comment]
0.65版本已经修复，谢谢你的issue

**Comment by liguanhan** [comment]
作者牛逼!作者666!为作者打Call~

**Comment by liguanhan** [comment]
作者我看你好像也在研究Flutter,你什么时候有空能不能开源一个flutter-SmartRefreshLayout(好像好点贪得无厌),如果有了我马上去给个star!

**Comment by 2534290808** [comment]
这是我开发的flutter包，求赞https://github.com/flutter-studio/flutter-icons
