### ISSUE TITLE
上拉加载没有效果

### ISSUE THREAD

**Issue by 13980519619** [react-native-studio/react-native-SmartRefreshLayout#27]
flatlist上拉加载更多没有效果，都没解决，怎么就关了呢？不使用这个，加载更多就正常

**Comment by 2534290808** [comment]
能提供版本信息吗

**Comment by 13980519619** [comment]
react-native 0.54.0
大神，使用这个组件。这个组件只是解决了下拉刷新，缺影响了正常的下拉刷新，我是使用的flatlist。应该是flatlist和renderScrollComponent里面的ScrollView冲突了。

**Comment by 2534290808** [comment]
能贴一下你的代码吗？

**Comment by 13980519619** [comment]
render() {
    log('[RefreshFlatList]  render  refreshState:' + this.props.refreshState)

    let {renderItem, ...rest} = this.props;
    let renderScrollComponent =null;
    if(this.state.isShowRefreshControl == true){
        // renderScrollComponent=
        // (props)=>
        // <ScrollView
        //     style={{flex:1}}
        //     refreshControl={<SmartRefreshControl
        //         ref={ref => this.rc = ref}
        //         HeaderComponent={<DefaultHeader/>}
        //         onRefresh={() => {
        //             this.onHeaderRefresh(this.rc.finishRefresh);
        //         }}
        //     />}
        // />
    }
    return (
        <FlatList
            //renderScrollComponent={renderScrollComponent}
            ref={this.props.listRef}
            data = {this.props.data}
            extraData = {this.props.extraData}
            onRefresh={this.onHeaderRefresh.bind(this)}
            onEndReached={this.onEndReached.bind(this)}
            refreshing={this.props.refreshState == RefreshState.HeaderRefreshing}
            ListFooterComponent={this.renderFooter(this)}
            onEndReachedThreshold={0.1}
            renderItem={renderItem}
            {...this.props}
            //onScroll={this.onScroll.bind(this)}
        />
    )
}
------------------ 原始邮件 ------------------
发件人: "黎明"<notifications@github.com>;
发送时间: 2018年12月12日(星期三) 上午10:31
收件人: "react-native-studio/react-native-SmartRefreshLayout"<react-native-SmartRefreshLayout@noreply.github.com>;
抄送: "梦在老特拉福德"<2465205038@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [react-native-studio/react-native-SmartRefreshLayout] 上拉加载没有效果 (#27)




能贴一下你的代码吗？

**Comment by 13980519619** [comment]
我拷贝你的renderScrollComponent代码测试，可以了。
应该我写的renderScrollComponent写的有问题。
