### ISSUE TITLE
请问下，加上导航条以后，下拉刷新怎样隐藏在导航条下方？谢谢

### ISSUE THREAD

**Issue by Maisoo1** [react-native-studio/react-native-SmartRefreshLayout#28]
<img width="308" alt="wechatimg342" src="https://user-images.githubusercontent.com/17640738/50290699-6e69fc80-04a7-11e9-933d-fbdab1ad5d06.png">
类似上图，加上导航条后，希望下拉条能隐藏在导航条下方

**Comment by qxj006** [comment]
同问怎么解决

**Comment by 2534290808** [comment]
头部设置zIndex可解决
