### ISSUE TITLE
react-native 0.59版本 UIManager['SmartRefreshLayout'] is no longer supported

### ISSUE THREAD

**Issue by cctvmikeowen** [react-native-studio/react-native-SmartRefreshLayout#35]
YellowBox.js:67 Accessing view manager configs directly off UIManager via UIManager['SmartRefreshLayout'] is no longer supported. Use UIManager.getViewManagerConfig('SmartRefreshLayout') instead，请问下该如何处理

**Comment by 2534290808** [comment]
0.6.7版本已经修复
