### ISSUE TITLE
修改了app的名称

### ISSUE THREAD

**Issue by JTR354** [react-native-studio/react-native-SmartRefreshLayout#6]
app名称被修改成智能刷新了

**Comment by supermanxiacheng** [comment]
我也遇到这个问题了，第一个提问者的意思是，自己的项目集成了SmartRreshLayout之后，主项目的app名字被改成了 智能刷新了。

**Comment by 2534290808** [comment]
变成了'SmartRefreshLayout'还是中文的‘智能刷新’？

**Comment by supermanxiacheng** [comment]
我这边是变成了中文的智能刷新了

**Comment by 2534290808** [comment]
具体请看我的示例Example

**Comment by RoarRain** [comment]
这个是SmartRefreshLayout造成的，SmartRefreshLayout的最新版本已经修复了
将

> 

dependencies {
    compile "com.facebook.react:react-native:+"
    compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.5'
    compile 'com.scwang.smartrefresh:SmartRefreshHeader:1.0.5'//没有使用特殊Header，可以不加这行
}

改成

dependencies {
    compile "com.facebook.react:react-native:+"
    compile 'com.scwang.smartrefresh:SmartRefreshLayout:1.0.5.1'
    compile 'com.scwang.smartrefresh:SmartRefreshHeader:1.0.5.1'//没有使用特殊Header，可以不加这行
}

即可
