### ISSUE TITLE
可以和react-native-mjRefresh 一起用吗，import Smart后会在iOS上报错

### ISSUE THREAD

**Issue by RoarRain** [react-native-studio/react-native-SmartRefreshLayout#7]
ExceptionsManager.js:73 Warning: Native component for "RCTDefaultHeader" does not exist

ExceptionsManager.js:73 Warning: Native component for "SmartRefreshLayout" does not exist

ExceptionsManager.js:65 Cannot read property 'translate' of undefined

**Comment by 2534290808** [comment]
使用Platform.OS === 'android'判断使用SmartRefreshControl

**Comment by RoarRain** [comment]
判断了 没用只要import 就会报错，

**Comment by RoarRain** [comment]
react-native-mjRefresh 怎么设置contentContainerStyle 没有用呀？

**Comment by 2534290808** [comment]
已经修复，v0.5.4

**Comment by 2534290808** [comment]
react-native-mjRefresh 怎么设置contentContainerStyle 没有用呀？该问题请到react-native-mjRefresh提issue，谢谢
